### ISSUE TITLE
Rotation of the Icon

### ISSUE THREAD

**Issue by Sulorb** [0n3byt3/Leaflet.MarkerPlayer#1]
Hello,

First of all sorry if that's not the place to do a suggestion of a new feature.

I'd like to be able to change the angle of the Icon moving from latLngA to latLngB.

I tried many things in vain, as this:

`  const angle = Math.atan2(to.lat - from.lat, to.lng - from.lng) * 180 / Math.PI;

    movement.setIcon(L.icon({ iconUrl: img, iconSize: [40, 40] }));
    movement.addTo(this.map).start();
    movement.on('progresschange', (e: any) => {
      e.target._icon.style.transform += `rotate(${angle}deg)`;
    })`
    

But it didn't work.
    
Is there any way to do it? For example showing a plane on the map would look way better if the plane has the correct orientation.

Thanks a lot,

**Comment by 0n3byt3** [comment]
@Sulorb  Hi 
first of all no problem at all, you are very welcome👍...
don't make it hard on yourself, just use [Leaflet.RotatedMarker](https://github.com/bbecquet/Leaflet.RotatedMarker) & [Leaflet.GeometryUtil](https://github.com/makinacorpus/Leaflet.GeometryUtil); on update you can do something like this:
`e.target.setRotationAngle(L.GeometryUtil.bearing(latLngA, latLngB));`
